name = "Colony Protocol: Elysian"
author = "MichaelHeaton"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ffef1850fa58d7d1371b58930dc8d3f54a75361ddaa0792d00ba5ca1b41bae4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
