name = "Colony Protocol: Elysian"
author = "MichaelHeaton"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eccd9e7e9972b211e956463ce8dca5929659ae741a623bb5ca25b1cf1779073c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
